server:
  port: 8762
spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: #eureka server 页面列表字段 status 显示ip
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  prefix: /api
  routes:
    api-identity:
      path: /identity/**
      serviceId: api-identity
      sensitive-headers:
      custom-sensitive-headers: true
    api-company:
      path: /company/**
      serviceId: api-company
      sensitive-headers:
      custom-sensitive-headers: true
    api-process:
      path: /process/**
      serviceId: api-process
      sensitive-headers:
      custom-sensitive-headers: true
    api-calculate:
      path: /calculate/**
      serviceId: api-calculate
      sensitive-headers:
      custom-sensitive-headers: true
    api-subject:
      path: /subject/**
      serviceId: api-subject
      sensitive-headers:
      custom-sensitive-headers: true

#  sensitive-headers:
